export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';
export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const USERDATA_UPDATED = 'USERDATA_UPDATED';
export const USERS_FAILURE = "USERS FAILURE";
export const USERS_REQUEST = "USERS REQUEST";
export const USERS_RECEIVED = "USERS RECEIVED";
export const REMOVE_USER_FAILURE = "REMOVE USER FAILURE";
export const REMOVE_USER_REQUESTED = "REMOVE USER REQUESTED";
export const REMOVE_USER_COMPLETED = "REMOVE USER COMPLETED";


